{
    'name': 'Reporte Libro Mayor, Diario, Balance general Personalizado',
    'version': '17.0.0.2',
    'category': 'Accounting/Reporting',
    'summary': 'Reporte de Libro Mayor, Diario y Balance general con estructura personalizada',
    'author': 'HW Constructor',
    "website": "https://www.hw.com.gt",
    'depends': ['account'],
    'data': [
        'security/ir.model.access.csv',
        'views/ledger_wizard_view.xml',
        'views/daily_wizard_view.xml',
        'views/balance_general_wizard_view.xml',
        'reports/report_general_ledger.xml',
        'reports/report_daily_journal.xml',
        'reports/report_balance_general.xml',
    ],
    'installable': True,
    'application': False,
    "license": "LGPL-3",
}